version: '3'

vars:
  site: 'benton.com'

tasks:
  peek:
    cmds:
      - unzip -Z1 {{.site}}
  clean:
    cmds:
      - rm -f {{.site}} && cp redbean-3.0.0.com {{.site}} && chmod +x ./{{.site}}
  dev:
    cmds:
      - task: build
      - task: run
  run:
    cmds:
      - chmod +x ./{{.site}}
      - sh -c ./{{.site}}
  build:
    cmds:
      - cd src && zip -R ../{{.site}} '*.lua' '*.html' '*.js' '*.css'
      - zip -R {{.site}} static/*
  deploy:
    cmds:
      - task: clean
      - task: build
      - task: run
